# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 ruff pygit2 requests
    - name: Check with flake8
      run: |
        flake8 src --max-complexity=10 --max-line-length=120 \
          --count --show-source --statistics
    - name: Check with ruff
      run: |
        ruff check src
    - name: Run unittest
      run: |
        python -m unittest discover -s src -v
